# Generated by Django 3.1.7 on 2021-03-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerveceria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cerveza',
            options={'ordering': ['marca', 'tipo'], 'verbose_name_plural': 'Cervezas'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name_plural': 'Marcas'},
        ),
        migrations.RemoveField(
            model_name='marca',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cerveza',
            name='descripcion',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='marca',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico'),
        ),
    ]
