# Generated by Django 3.1.7 on 2021-03-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerveceria', '0002_auto_20210305_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerveza',
            name='nombre',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='cerveza',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
