# Generated by Django 3.1.7 on 2021-03-05 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerveceria', '0003_auto_20210305_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cerveza',
            name='nombre',
        ),
    ]
