# Generated by Django 3.1.7 on 2021-03-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerveceria', '0004_remove_cerveza_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerveza',
            name='nombre',
            field=models.CharField(default="Boiwko's", max_length=50),
        ),
    ]
