# Generated by Django 3.1.7 on 2021-03-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerveceria', '0007_auto_20210305_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerveza',
            name='tipo',
            field=models.CharField(max_length=200),
        ),
    ]
