# Generated by Django 3.1.7 on 2021-03-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerveceria', '0008_auto_20210306_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerveza',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cerveza',
            name='tipo',
            field=models.CharField(max_length=600),
        ),
    ]
