# Generated by Django 3.1.7 on 2021-03-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerveceria', '0009_auto_20210306_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerveza',
            name='descripcion',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
